name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    environment:
      name: release
      url: https://pypi.org/p/cyberjake

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Build
      run: |
        make build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Build and publish to Fury.io
      env:
        GEM_TOKEN: ${{ secrets.GEM_TOKEN }}
      run: |
        twine upload dist/* --repository-url https://push.fury.io/cyb3r-jak3 -u $GEM_TOKEN -p ""

